# Generated by Django 4.1.2 on 2023-07-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.FloatField()),
                ('haggle', models.CharField(choices=[('Negotiable', 'Negotiable'), ('Unnegotiable', 'Unnegotiable')], default='Negotiable', max_length=50)),
                ('food_discription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='image')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('food_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
