# Generated by Django 4.1.2 on 2023-07-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('discription', models.TextField(blank=True, null=True)),
                ('crypto_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
    ]
